#!/usr/bin/env bash

shopt -s extglob

function install_packages {
	local packages=( 'ccache' 'automake' 'flex' 'lzop' 'bison' 'gperf' 'build-essential' 'zip' 'curl' 'zlib1g-dev' 'zlib1g-dev:i386' 'g++-multilib' 'git' 'python-networkx' 'libxml2-utils' 'bzip2' 'libbz2-dev' 'libbz2-1.0' 'libghc-bzlib-dev' 'squashfs-tools' 'pngcrush' 'schedtool' 'dpkg-dev' 'liblz4-tool' 'make' 'optipng' 'maven' 'libssl-dev' 'pwgen' 'libswitch-perl' 'policycoreutils' 'minicom' 'libxml-sax-base-perl' 'libxml-simple-perl' 'bc' 'libc6-dev-i386' 'lib32ncurses5-dev' 'x11proto-core-dev' 'libx11-dev' 'lib32z-dev' 'libgl1-mesa-dev' 'xsltproc' 'unzip' 'gcc-8' )
	local DISTRO_VERSION=`lsb_release -r | sed 's/.*\s//'`
	sudo dpkg --add-architecture i386
	wget -qnc https://dl.winehq.org/wine-builds/winehq.key
	sudo apt-key add winehq.key && fm winehq.key
	if [[ "${DISTRO_VERSION}" = "18.10" ]]; then
		sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ cosmic main'
	elif [[ "${DOSTRO_VERSION}" = "18.04" ]]; then
		sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main'
	else
		sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ xenial main'
	fi
	sudo apt-get update
	pkg install "${packages[@]}"
}

function setup_gpgkeys {
	gpg_keys=( 'github.asc' )
	for gpgk in "${gpg_keys[@]}"; do \
		gpg --import `pwd`/keys/$gpgk; \
	done
}

function setup_confs {
	[[ ! -d ~/infection ]] && \
		mkdir -p ~/infection/tests/{shellscripts,c}
	[[ "$(grep -o "infection" "${HOME}/profile")" != *infection* ]] && \
		printf "%b" "PATH=$HOME/infection/tests/c:$HOME/infection/tests/shellscripts:$PATH" >> "$HOME/profile"
	cp `pwd`/.gitconfig ~/.gitconfig
	cp `pwd`/shells/bash/@(.|)[a-zA-Z]* ~/
	setup_gpgkeys
}

install_packages
setup_confs
