#!/usr/bin/env bash

shopt -s extglob

[[ -e `pwd`/setup.cfg ]] && {
	set -a
	. `pwd`/setup.cfg
	set +a
} || exit 1

#function install_gpgkeys {
#	gpg_keys=( 'git.asc' )
#	for gpgk in "${gpg_keys[@]}"; do \
#		sudo gpg --import `pwd`/keys/$gpgk; \
#	done
#	unset gpg_keys
#}

function install_confs {
	cp `pwd`/.gitconfig ~/.gitconfig
	cp `pwd`/shells/bash/@(.|)[a-zA-Z]* ~/
}

[[ -n "${install_confs}" ]] && install_confs
#[[ -n "${install_gpgkeys}" ]] && install_gpgkeys
